### ISSUE TITLE
rewrite not working

### ISSUE THREAD

**Issue by jagottsicher** [Shadouts/PiNode#1]
I use PiNode to gather some experience to use JSON and due to its simplicity I is reaaly nce to understands, but the rewrite rule in my .htaccess does not work:
```
RewriteEngine On
RewriteRule ^/([A-Za-z]+)$ /page/$1.html [NC,L]
```
Any Idea what the issue could be? I also set rewritebase to /, didn't work.

**Comment by Shadouts** [comment]
Have you ensured that override files have been enabled in Apache? In the config, under your site's <Directory> entry put:
AllowOverride All

Then restart apache.

**Comment by jagottsicher** [comment]
should be fine, cause I run serveral vhosts with that apache and they all don't shw that problem. But I will check.
